### ISSUE TITLE
`-update` a changed file does not overwrite the xml file

### ISSUE THREAD

**Issue by Edditoria** [nicjansma/checksum-verifier#1]
Thanks for your work and good license that I can use it on my repo.

I found a problem the `-update` switch does not overwrite the existing xml file.

# Reproducing The Problem

1. In C:\test\data\test.txt, write content "123" and save
2. In data directory, do `C:\test\program\ChecksumVerifier.exe -update -db "C:\test\report.xml"`
3. In C:\test\data\test.txt, update content to "123456" and save
4. In data directory, do `C:\test\program\ChecksumVerifier.exe -update -db "C:\test\report.xml"`
5. It says "No changes required".
6. Do `C:\test\program\ChecksumVerifier.exe -verify -db "C:\test\report.xml"`
7. It says "Mismatch" (`echo %errorlevel%` gives -1)

Does it work by design? Is there any switch to force overwrite the xml file?

Thanks.

**Comment by nicjansma** [comment]
@Edditoria you're right, today it doesn't check existing files to see if their contents have been updated during `-update` -- it only checks for new or missing files.  It only verifies file contents during `-verify`.  

This was mostly done for performance reasons.  In my use case, I don't expect files to change (so they're verified first with `-verify`), and once they're verified I can add new files via `-update`.

It would be a relatively quick change to add support for this.  I might recommend a new option along with `-update`: `-updateExisting`.

If you have time to make this change, that would be great.  Otherwise, I can try to get to it sometime soon.

**Comment by oriceon** [comment]
Hi @nicjansma . Any news on that? :)

**Comment by nicjansma** [comment]
Just released v1.1.0 with this option `-updateExisting`
